- hosts: all
  become: true
  tasks:
    - name: "system update"
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: "install basic tools"
      apt:
        name: ['net-tools']
        state: latest